### ISSUE TITLE
[Installation] Can't download data models

### ISSUE THREAD

**Issue by joanitachong** [activityMonitoring/biobankAccelerometerAnalysis#150]
During installation, in utilities/downloadDataModels.sh , It says "wget: command not found" in lines 20-25 and 30. 

Then I tried accessing the "downloadDir" website from where the files are downloaded and I don't have access to it. It says "Forbidden: You don't have permission to access /aidend/accModels/ on this server."

What can I do?

**Comment by chanshing** [comment]
I would seem that you don't have `wget`. Are you using Windows? Mac?

**Comment by joanitachong** [comment]
I have Mac

**Comment by chanshing** [comment]
I think you'll need to get `wget` first. I found this https://www.jcchouinard.com/wget/#:~:text=download(url)%20filename-,Debug%20Wget%20Command%20Not%20Found,that%20you%20installed%20wget%20properly.
@angerhang Any ideas?

**Comment by joanitachong** [comment]
I just got wget, but I'm still having the same problem. I can't access the "downloadDir" ( http://gas.ndph.ox.ac.uk/aidend/accModels/ ). I'm still "Forbidden: You don't have permission to access /aidend/accModels/ on this server."

**Comment by chanshing** [comment]
Are you still not able to run `bash utilities/downloadDataModels.sh`?

**Comment by joanitachong** [comment]
It runs, but it can't find the download directory.

![Screenshot 2021-04-17 at 12 42 58](https://user-images.githubusercontent.com/57191772/115111921-ae0f5900-9f7a-11eb-8b00-8ce713dd9d15.png)

**Comment by joanitachong** [comment]
I mean, the first 5 lines with (No such file or directory) are normal because those files don't exist. But the remaining ones (Box 1) should work. But they don't work because I don't have access to the download directory (Box 2 and 3). 

<img width="762" alt="Screenshot 2021-04-17 at 12 48 32" src="https://user-images.githubusercontent.com/57191772/115112166-27f41200-9f7c-11eb-83f0-087045a84ed5.png">

<img width="836" alt="Screenshot 2021-04-17 at 12 54 01" src="https://user-images.githubusercontent.com/57191772/115112178-2f1b2000-9f7c-11eb-9ec2-4ef0ac333b91.png">

**Comment by chanshing** [comment]
I don't think the access is the problem because I also don't have it and can still download the files just fine. You can have no access to the directory while having access to particular files. From what you showed, it seems that the problem is still `wget`.
Alternatively, you can try from your browser:

http://gas.ndph.ox.ac.uk/aidend/accModels/doherty-may20.tar
http://gas.ndph.ox.ac.uk/aidend/accModels/willetts-may20.tar
http://gas.ndph.ox.ac.uk/aidend/accModels/walmsley-nov20.tar
http://gas.ndph.ox.ac.uk/aidend/accModels/doherty-jan21.tar
http://gas.ndph.ox.ac.uk/aidend/accModels/willetts-jan21.tar
http://gas.ndph.ox.ac.uk/aidend/accModels/walmsley-jan21.tar

**Comment by joanitachong** [comment]
You are right. I was able to download the files from the browser, so the problem must be the `wget`. But I got the files, so thanks!
