### ISSUE TITLE
sleep algorithm

### ISSUE THREAD

**Issue by JianWang2016** [activityMonitoring/biobankAccelerometerAnalysis#44]
Hi Aiden,

I don't seem to be able to find out how sleep is determined.  I noticed some people in our cohort have very little sleep.  Now I admit that our people don't have perfect sleep patterns to start with but if there is any way to adjust the sensitivity of the algorithm so it is more forgiving for sleep detection.  People of different ages and health conditions would have different sleep quality and I wonder if it is feasible to set such as excellent, good, fair, poor sleep quality and adjust algorithms accordingly.  People with poor sleep quality still sleep more than 2 or 3 hours each night on a regular basis.  Any thoughts on this?

**Comment by aidendoherty** [comment]
Hi @JianWang2016 

Unfortunately there is currently no easy way to adjust the sensitivity of the algorithm with regard to classifying sleep vs wake. The nature of the machine learning method means that for each 30sec time window, a single class prediction is made (i.e. sleep vs sedentary vs tasks-light vs...). A probabilistic output is not made (i.e. number of trees that 'vote' for sleep vs not). It is in theory possible to have a probabilistic output, but there are some downsides:
 i) it would add a lot of complexity, particularly training a hidden markov model with an input matrix of probabilities, rather than an input state sequence vector
 ii) it would have multiple knock-on consequences on the rest of the data processing pipeline

If it is ok, I propose to close this issue for now based on the above reasons.

However I can share some longer-term hope. Our group are currently conducting a major sleep polysomnography validation study in a larger and much more diverse set of participants. It's hard to predict when these new methods might be available - but I do expect this to offer a good (or at least well quantified) improvement on the current methods (which are still fit-for-purpose at present).

Best wishes, and many thanks for all your helpful feedback thus far - it is very much appreciated,
Aiden
